### ISSUE TITLE
[Question] Moving Stream from Client Constructor

### ISSUE THREAD

**Issue by zogot** [clue/php-ami-react#13]
Hey. Been using your library as reference. What would you say about moving the Stream $stream from the __construct() of Client. https://github.com/clue/php-ami-react/blob/master/src/Client.php#L25

Instead have a setStream method that can be called in here: https://github.com/clue/php-ami-react/blob/master/src/Factory.php#L41.

This opens up to making the Client instance before the Stream has connected. Then you can use ZeroMQ to send commands from a Web Interface for example as now you can reference something like

``` php
$zeromq->on('message', array($client, 'onMessage'));
```

Could there perhaps be something I'm missing?

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*
