### ISSUE TITLE
Is php-ami-react ready for production?

### ISSUE THREAD

**Issue by striketest** [clue/php-ami-react#25]
Hi :)

I am just wondering how many concurrent calls have you tested with php-ami-react? is it ready for a production?

I would like to write a predictive dialler script and it will run 24/7 on the background. There will be about 200-300 concurrent calls and a lot of agents at the call center. Script should detect individual call event in real time. 

A script would listen some events and do some actions with combination of mysql query (select / update). 

Thanks!

**Comment by clue** [comment]
Thanks for posting your questions @striketest! :+1: 

I encourage you to give this library a try and find out yourself :-)

> Is php-ami-react ready for production?

We've been using this library in a mission-critical setup for more than 6 months now have not experienced a single problem so far :)

> how many concurrent calls have you tested with php-ami-react?

This lib doesn't really handle telephony calls at all, it merely processes the events generated by Asterisk. You can control which events are sent to you during `login()` or using the `events()` method.

By default, Asterisk sends a few events for each call (channel information, subscriber states etc.). I wouldn't expect this to take a significant amount of processing time though, the channel encoding is probably significantly more expensive.

Benchmarking this has never been a top priority for me personally, but judging from the stats obtained from my other project (clue/php-redis-server), I estimate this lib should easily be able to handle 10000+ events per second.

If you happen to give this a try, feel invited to share your findings :)

> 200-300 concurrent calls

Estimating some very rough numbers here:

* Approximately 10 events per call
* `*` 300 concurrent calls
* `/` 60s estimated average call duration 
* `=` 50 events per second

So there should still be plenty room even if my estimations are off by 100% :-)

> run 24/7 on the background

Monitoring is key, I would say. I've never experienced any major flaws in this lib myself, but better be safe than sorry :)
