### ISSUE TITLE
installation error enniel/ami 2.1.0 requires clue/ami-react ~0.3.1 -> satisfiable by clue/ami-react[v0.3.1] but these conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by mohammed-najeeb** [clue/php-ami-react#33]

**Comment by clue** [comment]
What is your question again? :-)

I'm not sure this is an issue in this library, so I'm closing this for now. Please feel free to come back with more details if this problem persists and we can reopen this :+1:
