### ISSUE TITLE
Library configuration for production deployment

### ISSUE THREAD

**Issue by vjaro** [clue/php-ami-react#43]
Hi Christian,

I have been using this library on an application that i am making. I have stumbled on this library just a few weeks go and i must say that by far this is the most developer friendly library i have encountered among other asterisk php libraries. This is coming from a developer with less than 2months of experience working on Asterisk. All of the use cases that was required for my application was easily done. You made my work really easy. The most interesting part really for me is that there is just a minimal to zero configuration done on the Asterisk server. This might seem little but for every beginner out there it will be a huge relief since studying asterisk will take roughly a year in just to learn the basics of asterisk.

Now to my questions, is there a configuration to deploy this application? I am on the process of deploying my app into a production server and
i want to make sure that the event listeners should automatically register whenever the asterisk server restarts (if the connection was closed). Right now when the connection was closed, i have to manually
start the script for the event listeners to be registered.
I was thinking of using nohup to automate this process, but i want to hear your thoughts first for me to decide the optimal solution for deployment. Thanks!

**Comment by clue** [comment]
Thank you for the feedback and for the kind words!

This library has been used in production for years in a number of projects. This means that this library is known to be stable and has not caused any unexpected behavior that I'm aware of. As with pretty much anything, if you want to put this into production, monitoring is key. Depending on your particular use case, this means that you may either let your program die if an error occurs and then simply restart or you may simply use code to reconnect on a "close" event.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by rodrigowbazevedo** [comment]
Hi @vjaro I had the same issue in same applications, first I tried to use supervisord, it worked fine in some cases but if the asterisk take too long to restart supervisord reach his max retries and stop, now I'm using my AMI scripts inside a docker container and I just need to put `restart: always` inside my docker-compose config and everything is working fine.

**Comment by clue** [comment]
Thanks for reporting back @rodrigowbazevedo! :+1: 

For the reference: You can also user supervisord's configuration to set [`startretries = 1000`](http://supervisord.org/configuration.html#program-x-section-settings).
