### ISSUE TITLE
createAction sends same ActionId with every call

### ISSUE THREAD

**Issue by ceoxantek** [clue/php-ami-react#44]
createAction appends an ActionID to every call, but it is always returning the same value (2).
It does not seem to be possible to override it like this:
$client->createAction('Setvar',["Variable"=>"DEVICE_STATE(Custom:$device)","Value"=>$state,'ActionID' =>'102'])

**Comment by ceoxantek** [comment]
I changed the client creatAction to 
$args = array('Action' => $name, 'ActionID' => rand(0,9999)) +$args;
This gives me a random ActionId each time

**Comment by ceoxantek** [comment]
A better solution probably is to let the user send an actionId, and use a standard routine if one is not sent.

**Comment by clue** [comment]
Thank for filing this issue! The `createAction()` method should take care of creating a unique "ActionID" because this value is also used to match incoming response messages. What is the motivation for explicitly sending a custom value?

If you really want to do this, you can also create the `Action` yourself like this:

```php
$action = new Action(array(
    'Action' => 'Setvar',
    'Variable' => 'DEVICE_STATE(Custom:$device)',
    'Value' => $state,
    'ActionID' => '102'
));
```

I hope this helps :+1:

**Comment by ceoxantek** [comment]
I tried sending an ActionID like below, but it did not work. Still sent 
the predetermined ID.


My situation is somewhat unique:

I am reading the output of astmanproxy server, selecting specific 
actions and then sending a SetVar to one of several servers.

So I am firing up a new factory each time and sending the setVar.

I was having trouble debugging my code because I kept getting the same 
ActionID each time I fired up a new process.

If what you are suggesting below would work, that would solve my issue.


Bill

**Comment by clue** [comment]
Interesting use case :-)

The `request(Action $action): PromiseInterface` method simply takes the given `Action` object with its assigned "ActionID" and does not modify it. This should allow you to pass any custom `Action` object with any custom "ActionID".

**Comment by ceoxantek** [comment]
Does this action create look like it would work?
$client->createAction('Setvar',["Variable"=>"DEVICE_STATE(Custom:$device)","Value"=>$state,'ActionID' =>'102'])

**Comment by clue** [comment]
The `createAction()` method is only a helper method to *create* an `Action` (it will not *send* it). This method will overwrite your "ActionID" value automatically, you you'll likely have to build the `Action` object manually as given above.

If you have your `Action` object, you can simply pass it to the `request()` method which will actually *send* it (and will not *modify* it).

I hope this helps :+1:

**Comment by ceoxantek** [comment]
Here is what I am sending:

$action = 
$client->createAction('Setvar',["Variable"=>"DEVICE_STATE(Custom:$device)","Value"=>$state,"ActionID"=>'999']);
             print_r($action);
             $client->request($action)->then(
                 function (Response $response) {
                     // response received for ping action
                     print"response is".print_r($response,true);
                 },

And here is what I am getting:

Clue\React\Ami\Protocol\Action Object
(
     [fields:protected] => Array
         (
             [Action] => Setvar
             [ActionID] => 2
             [Variable] => DEVICE_STATE(Custom:SIP/globalpops)
             [Value] => INUSE
         )

)
response isClue\React\Ami\Protocol\Response Object
(
     [fields:protected] => Array
         (
             [Response] => Success
             [ActionID] => 2
             [Message] => Variable Set
         )

)

**Comment by clue** [comment]
Please read my last post carefully, the "ActionID" SHOULD NOT be passed to `createAction()`! If you want to assign a custom "ActionID", you have to use `new Action($args)` instead.

**Comment by ceoxantek** [comment]
OK, got it. Sorry to be so dense.

**Comment by ceoxantek** [comment]
Christian:


Could use your advice on something.

I am trying to get events from an asterisk AMI and then send a setVar 
back to that server.

I can get the events alright, but when I try to reply, the variable 
$client is always out of scope.

Code fragment:


$client->on('event', function (Event $event) {
             global $server3, $client;


             if($event->getName() == 'DeviceStateChange' && 
!strstr($event->getFieldValue('Device'),"Custom")
                     && !strstr($event->getFieldValue('Device'),".") && 
!strstr($event->getFieldValue('State'),"UNAVAILABLE")){
                 //echo $server2.' Event: ' . $event->getName() . ': ' . 
json_encode($event->getFields()) . PHP_EOL

           $action = new Clue\React\Ami\Protocol\Action(array( ...

           $client->request($action) ...

Always returns variable client not found.

Is there any way to pass $client inside the 'on'


Thanks in advance

Bill

**Comment by clue** [comment]
It looks like you're missing the `use ($client)` for your closure here: `$client->on('event', function (Event $event) use ($client) {`.

I hope this helps :+1:

**Comment by ceoxantek** [comment]
Perfect thank you.


Bill
