### ISSUE TITLE
AMI connection persistence

### ISSUE THREAD

**Issue by vjaro** [clue/php-ami-react#46]
Hi Christian,

I have setup an Asterisk Server with FreePbx and another server for the Asterisk Events Listeners.
So what i wanted to do is to be able to persist connections or be able to reconnect to the AMI after it was closed. 

The way i am executing the event listeners is via an entrypoint through command line as a bash command Ex. `./doEventListeners` or as a php script `php doEventListeners.php`

Everytime the AMI connection closes, i have to execute the similar script.
Is there a way i can efficiently do this? I'm open to suggestions.

Also, with the current setup (Server 1 with Asterisk and Server 2 for event listeners), i am not able to record call using MixMonitor action.  However, when the Asterisk and event listeners are on a same server, MixMonitor just works fine. Is this the normal behavior?

Thanks

**Comment by clue** [comment]
Hi @vjaro, thank you for these very good questions!

This project uses "persistent" connections by default, i.e. it does not close the underlying connection unless you explicitly tell it to do so or if the remote side closes the connection. You may use ping messages ("keep alive", see also #14) to make sure the remote side can detect that the connection is still active.

Note that the remote side can still close the connection for a number of reasons (system reboot, software restart etc.) and this project supports detecting this through the `close` event. It is up to you to handle this situation for your specific use case. By default, the connection will simply be closed and your event-loop may exit if it does not have anything else to do. This is common setup and allows you to simply monitor and respawn your process if it dies.

As an alternative, you may also listen for the `close` event and create a new connection to your Asterisk server. This way, the process will keep running and it's up to you to handle reconnection handling. How you want to handle this depends on your particular use case and is probably out of scope of this project.

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

Regarding `MixMonitor` (https://wiki.asterisk.org/wiki/display/AST/Application_MixMonitor), I'm not aware of any limitations. You may want to check your AMI permissions and if you find that there's an issue in this library, please post this as a new bug issue and I'm happy to look into this 👍 

I hope this helps 👍

**Comment by vjaro** [comment]
Hi @clue, 
I have applied your suggestion to detect the close event and added a 10 second delay for ami reconnections. Plus i have configured the scripts to be runnable as a service using supervisord and so far so good. Connections are persisted and no interruptions.

Regarding the MixMonitor action, it needs to have a physical file fore the recording to be saved on the Asterisk server itself.
Bad news is we can't download the call recording through AMI scripts. It would be good if we can have this functionality. I have created a workaround so that i can fetch the recordings and upload into a client server.

Thank you so much for your help!

**Comment by clue** [comment]
Happy to hear you've got your keep-alive logic implemented 👍 

The MixMonitor action allows you to pass a filename or path (https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerAction_MixMonitor and https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Application_MixMonitor) to write to, so I would recommend using a path that you can access through some other means. I'm not aware of any AMI/Asterisk command to download a file, so your best bet would be using like an additional webserver etc. to expose these files.

I hope this helps 👍

**Comment by clue** [comment]
For the reference: Technically, you could also execute the `Command` action to run arbitrary shell commands (`! cat /path/recording.wav`), but while this does work from a local Asterisk CLI, this is explicitly disabled when running through AMI: http://lists.digium.com/pipermail/asterisk-users/2011-March/260339.html.

A number of work-arounds for this exist, such as adding the command to your dialplan and assigning the results to a variable (or by adding this through AMI's AGI interface) etc., but this depends entirely on what you want to achieve.

As a rule of thumb, using an additional webserver instead of processing the file download through AMI is probably a good idea 👍
