### ISSUE TITLE
Please teach me to use the examples from this library

### ISSUE THREAD

**Issue by Goodnato** [clue/php-ami-react#47]
Please teach me step by step to run the websocket just to see the examples. There are 3 and I do not know how it works. Please friends I beg when I find out how the websocket runs the rest I learn.

Please, now teach me step by step how I run the examples https://github.com/clue/php-ami-react/tree/master/examples it's my dream to use this library please teach me step 1. step 2 , step 3 until I see the result of the example

**Comment by clue** [comment]
HI @Goodnato and welcome to ReactPHP :-)

It's a bit unclear what you're trying to achieve from the details you've posted.

This project implements communication with Asterisk's AMI, it does not implement websockets. You can execute any of the examples by running each on the command line. For example, this one prints a list of currently active SIP peers ("phone calls"):

```
$ php examples/peers.php user:secret@localhost
```

If you're looking for a websocket implementation, consider taking a look at http://socketo.me/ instead.

I hope this helps :+1:

**Comment by Goodnato** [comment]
Thank you for replying, my friend. Forgive me I confused, I saw `$loop->run()` and found it was websocket.

I put `php examples/peers.php user:user@192.168.0.76:8088` and gave the error `Could not open input file: examples/peers.php.
`
I installed it this way: `composer require clue/ami-react:^0.4`

My Asterisk is working fine and I have already set up `http.conf` and `manager.conf`. When I use socket I get answers. I want to use your library now. Can you see why you did not run the peers.php or commands.php example?

I use xampp PHP 7.2. The composer.json file looks like this:
`{
    "name": "clue/ami-react",
    "description": "Streaming, event-driven access to the Asterisk Manager Interface (AMI), built on top of ReactPHP",
    "keywords": ["Asterisk Manager Interface", "AMI", "async", "ReactPHP"],
    "homepage": "https://github.com/clue/php-ami-react",
    "license": "MIT",
    "authors": [
        {
            "name": "Christian Lück",
            "email": "christian@lueck.tv"
        }
    ],
    "require": {
        "php": ">=5.3",
        "evenement/evenement": "^3.0 || ^2.0 || ^1.0",
        "react/event-loop": "^1.0 || ^0.5 || ^0.4 || ^0.3",
        "react/promise": "^2.0 || ^1.1",
        "react/socket": "^1.0 || ^0.8.2"
    },
    "require-dev": {
        "clue/block-react": "^1.2",
        "phpunit/phpunit": "^5.0 || ^4.8"
    },
    "autoload": {
        "psr-4": { "Clue\\React\\Ami\\": "src/" }
    }
}`

I also wanted to know how to put the answer in a variable. `$handle = $client->event()`;

**Comment by clue** [comment]
You need to adjust the paths to match your project. Or just copy-paste the contents of one of the examples into a file in your project directory and run it locally. Once this is running, you can then use this as a starting point to see how this library can be used. If you want to view events instead of your SIP peers, you may want to start with the `events.php` example.

**Comment by Goodnato** [comment]
Worked perfectly. When you run the commands.php example, `Client connected appears. Use STDIN to send CLI commands via asterisk AMI`. I do not know what to put here anymore kkkkkkkk.

Sorry, I'm a student. What I had in mind was to put SIPpeerstatus and pop up all the peers. It's possible?
In case I wanted to put `var_dump(SIPpeerstatus)` and see in the browser the result.

Congratulations on the project, it's incredible. When I acquire knowledge I will help. Congratulations on winning the soccer world cup in Brazil and congratulations on having the best beer in the world.

**Comment by clue** [comment]
> It worked out perfectly here.

Happy to hear you've got this working!

> Just one last thing, how do I get access to this data? How do I get the json? Should I connect via ajax or even php to get access to the AMI request response?

I see you've just opened #48, so let's continue this discussion there :+1:
