### ISSUE TITLE
How to show async response in web page? (blocking integration)

### ISSUE THREAD

**Issue by Goodnato** [clue/php-ami-react#48]
All reactphp videos make application by console. How do I integrate to my site? I want to create a table and show the connected peers for example. On the console I can see the peers but how do I get json for my html?

Please, I'm worn out of worry.

**Comment by clue** [comment]
This library provides you a powerful, async API by default. If, however, you want to integrate this into your traditional, blocking environment, you should look into also using [clue/reactphp-block](https://github.com/clue/reactphp-block).

The resulting blocking code could look something like this:

```php
use Clue\React\Block;

function foo()
{
    $loop = React\EventLoop\Factory::create();
    $factory = new Factory($loop);

    $target = 'name:password@localhost';
    $promise = $factory->createClient($target)->then(function (Client $client) use ($loop) {
        $collector = new ActionSender($client);
        $ret = $collector->sipPeers()->then(function (Collection $collection) {
            return $collection->getEntryEvents();
        });
        $client->end();
        return $ret;
    });

    return Block\await($promise, $loop, 5.0);
}
```

I hope this helps! :+1:

**Comment by Goodnato** [comment]
Thank you very much. Have a nice day!
